In [16]:
import pandas as pd
import numpy as np
import pickle
import json

In [17]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.5.2
Summary: A set of python modules for machine learning and data mining
Home-page: https://scikit-learn.org
Author:
Author-email:
License: BSD 3-Clause License

Copyright (c) 2007-2024 The scikit-learn developers.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: C:\Users\Aduhaiy\anaconda3\Lib\site-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: feature-engine, imbalanced-learn, yellowbrick

In [18]:
# Load Model

with open('num_cols.txt', 'r') as file_1:
  num_cols = json.load(file_1)

with open('cat_cols.txt', 'r') as file_2:
  cat_cols = json.load(file_2)

with open('best_rf_model.pkl', 'rb') as file_3:
  best_rf_model = pickle.load(file_3)

In [19]:
# Input data
data = {
    'CreditScore': [700, 820],
    'Geography': ["Germany", "Germany"],
    'Gender': ["Female", "Male"],
    'Age': [33, 29],
    'Tenure': [7, 5],
    'Balance': [130000, 97000],
    'NumOfProducts': [3, 1],
    'HasCrCard': [1, 0],
    'IsActiveMember': [1, 1],
    'EstimatedSalary': [85000, 90000]
}

df = pd.DataFrame(data)
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,700,Germany,Female,33,7,130000,3,1,1,85000
1,820,Germany,Male,29,5,97000,1,0,1,90000

In [20]:
# Splitt kolom
data_inf_num = df[num_cols]
data_inf_cat = df[cat_cols]
data_inf_num

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,700,33,7,130000,3,1,1,85000
1,820,29,5,97000,1,0,1,90000

In [25]:
#Gabungkan kembali kolom numerik dan kategorikal
data_final = pd.concat([data_inf_num, data_inf_cat], axis=1)

In [26]:
#Lakukan prediksi menggunakan model yang telah dimuat
predictions = best_rf_model.predict(data_final)

# Looping untuk memberikan gambaran jelas
churn_labels = []
for pred in predictions:
    if pred == 1:
        churn_labels.append('Churn')
    else:
        churn_labels.append('Tidak Churn')

#Tampilkan hasil prediksi
print(f"Hasil prediksi untuk data pertama : ", churn_labels[0])
print(f"Hasil prediksi untuk data kedua : ", churn_labels[1])

Hasil prediksi untuk data pertama :  Churn
Hasil prediksi untuk data kedua :  Tidak Churn